# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-29 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinci.User'),
        ),
    ]
