# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vinci', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='uid',
            new_name='user',
        ),
    ]
