# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vinci', '0002_auto_20161102_0109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.ImageField(upload_to='./filters')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_landscape', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinci.User')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='intent',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
