# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinci', '0003_auto_20161102_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
