# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinci', '0007_auto_20161111_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='path',
            field=models.FileField(upload_to='filters/'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='url',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
