# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinci', '0008_auto_20161111_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
