# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 06:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinci', '0009_filter_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 11, 29, 1, 6, 42, 55587)),
        ),
    ]
